# Generated by Django 4.2.14 on 2024-08-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_headnews_subject_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='headnews',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
