# Generated by Django 4.0.3 on 2024-08-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='org_name',
            new_name='instansi',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='language',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='verification',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='refleksi-j-photo'),
        ),
    ]
