# Generated by Django 4.0.3 on 2024-08-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_org_name_verification_instansi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='timezone',
        ),
    ]
