# Generated by Django 4.2.14 on 2024-08-14 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_verification_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='team',
        ),
        migrations.AddField(
            model_name='verification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
