# Generated by Django 4.0.3 on 2024-08-14 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_remove_verification_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='refleksi-j-user-photo'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_file', models.FileField(blank=True, null=True, upload_to='refleksi-j-module')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_file', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
