# Generated by Django 4.2.14 on 2024-08-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_verification_profile_photo_module'),
        ('core', '0007_remove_verification_profile_photo_and_more'),
    ]

    operations = [
    ]
