# Generated by Django 4.2.14 on 2024-08-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_merge_20240815_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
