# Generated by Django 4.2.14 on 2024-08-15 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_verification_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
