# Generated by Django 4.2.14 on 2024-08-21 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_remove_teacheragenda_subject_journal_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacheragenda',
            name='user_subject',
        ),
        migrations.AddField(
            model_name='subject',
            name='users',
            field=models.ManyToManyField(related_name='subjects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacheragenda',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject'),
        ),
        migrations.AddField(
            model_name='teacheragenda',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserSubject',
        ),
    ]
