# Generated by Django 4.2.14 on 2024-08-22 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_teacheragenda_user_subject_subject_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('komponen_wajib', 'Komponen Wajib'), ('penialaian_kesesuaian', 'Penilaian Kesesuaian')], max_length=255, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.module')),
            ],
        ),
    ]
