# Generated by Django 4.2.14 on 2024-08-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_moduleassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='chatpdf_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
