# Generated by Django 4.2.14 on 2024-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_module_chatpdf_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleassessment',
            name='category',
            field=models.CharField(blank=True, choices=[('komponen_wajib', 'Komponen Wajib'), ('penialaian_kesesuaian', 'Penilaian Kesesuaian'), ('suggestion', 'Suggestion')], max_length=255, null=True),
        ),
    ]
