# Generated by Django 4.2.14 on 2024-08-26 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_moduleassessment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
        ),
    ]
