# Generated by Django 4.2.14 on 2024-08-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_moduleassessment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reflectionquestion',
            name='show',
        ),
        migrations.RemoveField(
            model_name='reflectionquestion',
            name='subject_reflection',
        ),
        migrations.AddField(
            model_name='journal',
            name='question_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject'),
        ),
        migrations.AddField(
            model_name='journal',
            name='subject_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SubjectReflection',
        ),
    ]
