# Generated by Django 4.2.14 on 2024-08-26 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_subject_users_subject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
