# Generated by Django 4.2.14 on 2024-08-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_angketansweroption_angketquestion_angketresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angketquestion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
