# Generated by Django 4.2.14 on 2024-08-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_angketquestion_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angketresponse',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='angketresponse',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='angketquestion',
            name='option_end_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='angketquestion',
            name='option_range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angketquestion',
            name='option_start_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='angketquestion',
            name='option_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angketresponse',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.teacheragenda'),
        ),
        migrations.DeleteModel(
            name='AngketAnswerOption',
        ),
    ]
