# Generated by Django 4.2.14 on 2024-08-26 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_reflectionquestion_show_and_more'),
        ('core', '0019_subject_order'),
    ]

    operations = [
    ]
