# Generated by Django 4.2.14 on 2024-08-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_angketresponse_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angketresponse',
            name='answer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
