# Generated by Django 4.2.14 on 2024-08-29 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_merge_20240826_0913'),
        ('core', '0021_angketresponse_answer'),
    ]

    operations = [
    ]
