# Generated by Django 4.2.14 on 2024-08-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_angketresponse_agenda_angketsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angketresponse',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
