# Generated by Django 4.2.14 on 2024-08-28 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_angketresponse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angketresponse',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.angketsession'),
        ),
    ]
