# Generated by Django 4.2.14 on 2024-08-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_angketresponse_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angketresponse',
            name='name',
        ),
        migrations.AddField(
            model_name='angketsession',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
