# Generated by Django 4.2.14 on 2024-08-29 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_merge_20240829_1116'),
        ('core', '0025_remove_angketresponse_name_angketsession_name'),
    ]

    operations = [
    ]
