# Generated by Django 4.2.14 on 2024-08-30 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20240829_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='core.teacheragenda'),
        ),
    ]
