# Generated by Django 4.2.14 on 2024-08-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_20240829_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='refleksi-j-module'),
        ),
    ]
