# Generated by Django 4.2.14 on 2024-08-31 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_journal_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheragenda',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.teacheragenda'),
        ),
    ]
