# Generated by Django 4.2.14 on 2024-09-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_article_cover_image'),
        ('core', '0029_agendareference_alter_teacheragenda_reference'),
    ]

    operations = [
    ]
