# Generated by Django 4.2.14 on 2024-09-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_agendareference_alter_teacheragenda_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
