# Generated by Django 4.2.14 on 2024-09-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_merge_20240901_1930'),
        ('core', '0030_module_name'),
    ]

    operations = [
    ]
