# Generated by Django 4.2.14 on 2024-09-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_merge_0030_merge_20240901_1930_0030_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
