# Generated by Django 4.2.14 on 2024-09-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_angketquestion_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='angketsession',
            name='target',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=25, null=True),
        ),
    ]
